version: 0.1

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  post_build:
    commands:
      - mvn package
      - mv target/gcp-container-engine-demo-1.0-SNAPSHOT.jar ./
artifacts:
  files:
    - gcp-container-engine-demo-1.0-SNAPSHOT.jar
  discard-paths: yes
