version: 0.1

phases:
  build:
    commands:
      - mvn package
      - mv target/gcp-container-engine-demo-1.0-SNAPSHOT.jar ./
artifacts:
  files:
    - gcp-container-engine-demo-1.0-SNAPSHOT.jar
  discard-paths: yes
